---
title: |
  | Business Analytics  
  | Bonus point sheet - Answers
author: 'Venkata Subramani Renduchintala / matriculation number: 16-905-416'
date: "27.05.2018"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(MASS);
library(ggplot2)
library(csvread)
library(tidyverse)
```

```{r Load Survey.csv}
surveyCsvPath <- './survey.csv'
#print(surveyCsvPath)
s.studentAnswers <- read.csv2(surveyCsvPath, header = TRUE, sep = ",", row.names = "X", stringsAsFactors = FALSE)
summary(s.studentAnswers)
s.studentAnswers$id <- row.names(s.studentAnswers)

#print(s.studentAnswers)
```


## Exercise 1

### a) Solution:
##Use the package ggplot2 to create a point plot comparing the age and pulse of the participants. 
##Color each point according to the gender of the person and additionally label the axis appropriately. 
##Furthermore, change the color of the points such that males are highlighted with a dark blue color and females in dark red.
```{r Point Plot comparing age and pulse of participants}
#create the sample data frame with age and pulse of the participants
df <- data.frame(s.studentAnswers$Pulse, s.studentAnswers$Age, s.studentAnswers$Sex)
#omit NA values
df <- na.omit(df)

#Plot
t <- ggplot2::ggplot(data = df) + 
  geom_point(mapping = aes(x = df$s.studentAnswers.Age, y = df$s.studentAnswers.Pulse, color = df$s.studentAnswers.Sex), show.legend = TRUE, na.rm =TRUE, size = 1) 
t + labs(x="Age", y="Pulse", title = "Comparison of participant's Age to Pulse") + 
  scale_color_manual(name="Gender", values=c('darkred', 'darkblue'))
```
### b) Solution:
```{r}
 
```

## Exercise 2

...